const jobs=[
{title:"Responsable GRC Cybersécurité",company:"Groupe industriel",place:"Sophia Antipolis",contract:"cdi",pay:82000,tjm:0,role:"grc",tech:false,date:"2026-09-23",tags:["GRC","ISO 27001","Gouvernance","Senior"],why:"Très forte adéquation : gouvernance, GRC, pilotage et environnement senior."},
{title:"Consultant senior Gouvernance Cyber",company:"Cabinet de conseil",place:"Aix-en-Provence / remote",contract:"freelance",pay:0,tjm:750,role:"grc",tech:false,date:"2026-09-22",tags:["Gouvernance","Risk","Freelance","Portage"],why:"Mission orientée gouvernance avec TJM compatible avec le seuil."},
{title:"RSSI de filiale",company:"Groupe industriel",place:"Toulon",contract:"cdi",pay:90000,tjm:0,role:"rssi",tech:false,date:"2026-09-21",tags:["RSSI","Management","Risque","Réglementaire"],why:"Responsabilité de pilotage avec une dominante gouvernance plutôt qu'opérationnelle."},
{title:"Responsable Gouvernance IA",company:"Groupe de services",place:"Marseille / remote",contract:"cdi",pay:78000,tjm:0,role:"ia",tech:false,date:"2026-09-20",tags:["IA","Gouvernance","AI Act","Risk"],why:"Gouvernance, réglementation et gestion des risques."},
{title:"Responsable Sécurité Opérationnelle",company:"ESN",place:"Sophia Antipolis",contract:"cdi",pay:76000,tjm:0,role:"rssi",tech:true,date:"2026-09-19",tags:["SOC","SIEM","Incident","Technique"],why:"Dominante opérationnelle et technique : pénalisée ou exclue selon le filtre."},
{title:"Consultant Risk & Compliance Cyber",company:"Cabinet de conseil",place:"Remote France",contract:"freelance",pay:0,tjm:680,role:"risk",tech:false,date:"2026-09-18",tags:["Risk","Compliance","NIS2","DORA"],why:"Bonne correspondance gouvernance/compliance et mode freelance."},
{title:"DPO / Privacy Manager",company:"Entreprise numérique",place:"Aix-en-Provence",contract:"cdi",pay:72000,tjm:0,role:"dpo",tech:false,date:"2026-09-17",tags:["DPO","RGPD","Privacy"],why:"Piste de diversification ; à vérifier selon le niveau RGPD demandé."}
];
const $=x=>document.getElementById(x);
function score(j){let s=50,r=$("role").value,z=$("zone").value,c=$("contract").value,t=+$("tjm").value;if(r!=="all")s+=j.role===r?20:-10;if(c!=="all")s+=j.contract===c?8:-8;let p=j.place.toLowerCase();if(z!=="all"){let ok={sophia:p.includes("sophia"),toulon:p.includes("toulon"),aix:p.includes("aix"),remote:p.includes("remote")}[z];s+=ok?10:-4}if(j.contract==="freelance")s+=j.tjm>=t?10:-15;if(j.tech)s-=35;return Math.max(0,Math.min(99,s))}
function render(){let r=$("role").value,z=$("zone").value,c=$("contract").value,t=+$("tjm").value,hide=$("technical").checked,a=jobs.filter(j=>!(hide&&j.tech)&&!(r!=="all"&&j.role!==r)&&!(c!=="all"&&j.contract!==c)&&!(j.contract==="freelance"&&j.tjm<t)).filter(j=>{if(z==="all")return true;let p=j.place.toLowerCase();return z==="sophia"?p.includes("sophia"):z==="toulon"?p.includes("toulon"):z==="aix"?p.includes("aix"):p.includes("remote")}).map(j=>({...j,s:score(j)}));let q=$("sort").value;if(q==="date")a.sort((x,y)=>y.date.localeCompare(x.date));else if(q==="pay")a.sort((x,y)=>(y.pay+y.tjm)-(x.pay+x.tjm));else a.sort((x,y)=>y.s-x.s);$("resultCount").textContent=a.length;$("highCount").textContent=a.filter(j=>j.s>=80).length;$("jobs").innerHTML=a.map(j=>{let pay=j.contract==="freelance"?j.tjm+" €/j":Math.round(j.pay/1000)+" k€";return `<article class="job"><div><h3>${j.title}</h3><div class="company">${j.company} · ${j.place}</div><div class="tags"><span class="tag">${j.contract==="cdi"?"CDI":"Freelance / portage"}</span><span class="tag">${pay}</span>${j.tags.map(x=>`<span class="tag">${x}</span>`).join("")}</div><div class="why">${j.why}</div></div><div><div class="score ${j.s>=80?"high":j.s>=65?"mid":""}">${j.s}<span>/ 100 · compatibilité</span></div><div class="actions"><button class="btn secondary" onclick="toggle(this)">☆ Suivre</button><button class="btn" onclick="alert('V3 : ce bouton ouvrira le lien de l’annonce originale.')">Voir l'offre</button></div></div></article>`}).join("")||`<div class="panel"><b>Aucune offre ne correspond aux critères.</b><p>Élargissez la zone ou diminuez le TJM minimum.</p></div>`}
function toggle(b){b.textContent=b.textContent.startsWith("☆")?"✓ Suivie":"☆ Suivre";let n=[...document.querySelectorAll(".btn.secondary")].filter(x=>x.textContent.startsWith("✓")).length;$("savedCount").textContent=n+" suivie"+(n>1?"s":"")}
["role","zone","contract","tjm","technical","sort"].forEach(x=>$(x).addEventListener("input",render));$("reset").onclick=()=>location.reload();render();